import { COLORS, SIZES, SHADOWS, ICONS, TEXTS, BRS, BUTTONS, AVATARS } from './theme';
import { RESERVATIONS, AREAS, SHOPS, USERS, ALERTS, PETS, ACCOUNTS, SOCIALS, PLATFORMS } from './variable';
export { COLORS, SIZES, SHADOWS, ICONS, TEXTS, BRS, BUTTONS, RESERVATIONS, AREAS, SHOPS, USERS, ALERTS, PETS, AVATARS, ACCOUNTS, SOCIALS };